system:
  domain: gin-mall
  version: 1.0
  env: "dev"
  HttpPort: ":5001"
  Host: "localhost"
  UploadModel: "local"

mysql:
  default:
    dialect: "mysql"
    dbHost: "127.0.0.1"
    dbPort: "3306"
    dbName: "gin_mall"
    userName: "root"
    password: "root"
    charset: "utf8mb4"

#kafka:
#  default:
#    debug: true
#    address: localhost:9092
#    requiredAck: -1 # 发送完数据后是否需要拿多少个副本确认 -1 需要全部
#    readTimeout: 30 # 默认30s
#    writeTimeout: 30 # 默认30s
#    maxOpenRequests: 5  # 在发送阻塞之前，允许有多少个未完成的请求，默认为5
#    partition: 2 # 分区生成方案 0根据topic进行hash、1随机、2轮询

redis:
  redisDbName: 1
  redisHost: 127.0.0.1
  redisPort: 6379
  redisPassword:
  redisNetwork: "tcp"

cache:
  cacheType: redis
  cacheEmpires: 600
  cacheWarmUp:
  cacheServer:

email:
  validEmail: http://localhost:8080/#/vaild/email/
  smtpHost: smtp.qq.com:25
  smtpEmail: 1302997173@qq.com
  smtpPass: kmibjpfvgamxfggh  # 发送邮件邮箱的授权码

encryptSecret:
  jwtSecret: "LLLSecret"
  emailSecret: "EmailSecret"
  phoneSecret: "PhoneSecret"

# 七牛云存储相关配置
oss:
  AccessKeyId:
  AccessKeySecret:
  BucketName:
  QiNiuServer:


photoPath:
  photoHost: http://127.0.0.1
  ProductPath: /static/imgs/product/
  AvatarPath: /static/imgs/avatar/

es:
  EsHost: 127.0.0.1
  EsPort: 9200
  EsIndex: mylog

rabbitMq:
  rabbitMQ: amqp
  rabbitMQUser: guest
  rabbitMQPassWord: guest
  rabbitMQHost: localhost
  rabbitMQPort: 5672